document.write('<head>')
document.write('<meta charset="UTF-8">')
document.write('<meta name="Description" content="Если у вас очень большое желание победить и сильная воля, то нет в этом мире силы, которая может помешать вам!"/>')
document.write('<meta name="viewport" content="width=device-width, initial-scale=1">')
document.write('<title>Азимут Мытищи</title>')
document.write('<link rel="stylesheet" href="https://vovak2018.github.io/style/style.css">')
document.write('<link rel="shortcut icon" href="https://vovak2018.github.io/media/img/favicon.png" type="image/x-icon">')
document.write('<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css"> ')
document.write('<meta name="yandex-verification" content="1b14f4e3a89e4dcd" />')
document.write("<meta name='wmail-verification' content='45d6b2d6929fd664e83c50c46abd51a5'/>")
document.write('</head>')
