"use strict";
document.write('<div class="menuip">')
document.write('    <div class="butons">')
document.write('        <a href="https://github.com/vovak2018/vovak2018.github.io" class="github1">')
document.write('        <div class="fasebook"></div>')
document.write('        </a>')
document.write('        <a href="https://www.youtube.com/channel/UCJ8jTZ1fRguHVLLo0MN_JlA">')
document.write('            <div class="youtube"></div>')
document.write('        </a>')
document.write('        <a href="#top">')
document.write('            <div class="up" data-title="Наверх"></div>')
document.write('        </a>')
document.write('        <a href="https://vk.com/club88506679">')
document.write('            <div class="vk"></div>')
document.write('        </a>')
document.write('    </div>')
document.write('    <div class="cont"></div>')
document.write('</div>')
document.write('<div class="allmh">')
document.write('    <p>Мы в соцсетях:</p>')
document.write('    <div class="menuhed">')
document.write('<a href="https://github.com/vovak2018/vovak2018.github.io" class="github1">')
document.write('    <i class="fab fa-github"></i>')
document.write('</a> ')
document.write('        <a href="https://www.youtube.com/channel/UCJ8jTZ1fRguHVLLo0MN_JlA" class="youtube1">')
document.write('            <i class="fab fa-youtube"></i>')
document.write('        </a> ')
document.write('        <a href="https://vk.com/club88506679" class="vk1">')
document.write('            <i class="fab fa-vk"></i>')
document.write('        </a> ')
document.write('    </div>')
document.write('</div>')